const { ObjectId } = require('mongodb')
const mongoose = require('mongoose')
const User = require('./User')
const Journal = require('./Journal')

// from the proposed parameters, not included are:
// Color label (generate based on due date)
// Project Id (should be autogenerated in db)
const ProjectSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  startDate: {
    type: Date,
    required: false // changing to false for now as we don't have a field in addProject and aren't leveraging it
  },
  dueDate: {
    type: Date,
    required: true
  },
  status: {
    type: Boolean,
    required: true,
  },
  userId: {
    type: String,
    required: true
  },
  estimatedTime: {
    type: Number,
    required: true
  },
  TotalTime: {
    type: Number,
    required: true,
    default: 0,
  },
  description: {
    type: String,
    required: true
  },
  
})

module.exports = mongoose.model('Project', ProjectSchema)